version: '3.8'

services:
  aciplatform-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: aciplatform-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=aciplatform-db,1433;Database=AciPlatform;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=AciPlatform
      - Jwt__Audience=AciPlatformUsers
      - Jwt__ExpireHours=8
    networks:
      - aciplatform-network
    depends_on:
      - db

  aciplatform-frontend:
    build:
      context: ../AciPlatform_Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://sit.backend.nguyenbinh.info.vn/api
    container_name: aciplatform-frontend
    restart: unless-stopped
    networks:
      - aciplatform-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aciplatform-db
    restart: unless-stopped
    environment:
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    networks:
      - aciplatform-network
    volumes:
      - db-data:/var/opt/mssql/data

  nginx:
    image: nginx:latest
    container_name: aciplatform-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/nginx/ssl:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - aciplatform-network
    depends_on:
      - aciplatform-api
      - aciplatform-frontend

networks:
  aciplatform-network:
    driver: bridge

volumes:
  db-data:
