using AciPlatform.Application.DTOs;
using AciPlatform.Domain.Entities.RestaurantErp;

namespace AciPlatform.Application.Interfaces.RestaurantErp;

public interface IRestaurantErpService
{
    Task<RestaurantDashboardDto> GetDashboardAsync(string? companyCode);
    Task<IEnumerable<RestaurantFund>> GetFundsAsync(string? companyCode);
    Task<RestaurantFund> CreateFundAsync(RestaurantFundRequest request);
    Task<RestaurantFund> UpdateFundAsync(int id, RestaurantFundRequest request);
    Task DeleteFundAsync(int id);
    Task<IEnumerable<RestaurantCapitalContribution>> GetCapitalContributionsAsync(string? companyCode);
    Task<RestaurantCapitalContribution> CreateCapitalContributionAsync(CapitalContributionRequest request);
    Task<RestaurantCapitalContribution> UpdateCapitalContributionAsync(int id, CapitalContributionRequest request);
    Task DeleteCapitalContributionAsync(int id);
    Task<IEnumerable<RestaurantSetupExpense>> GetSetupExpensesAsync(string? companyCode);
    Task<RestaurantSetupExpense> CreateSetupExpenseAsync(SetupExpenseRequest request);
    Task<RestaurantSetupExpense> UpdateSetupExpenseAsync(int id, SetupExpenseRequest request);
    Task DeleteSetupExpenseAsync(int id);
    Task<IEnumerable<RestaurantMaterialGroup>> GetMaterialGroupsAsync(string? companyCode);
    Task<RestaurantMaterialGroup> CreateMaterialGroupAsync(MaterialGroupRequest request);
    Task<RestaurantMaterialGroup> UpdateMaterialGroupAsync(int id, MaterialGroupRequest request);
    Task DeleteMaterialGroupAsync(int id);
    Task<IEnumerable<RestaurantMaterial>> GetMaterialsAsync(RestaurantErpFilter filter);
    Task<RestaurantMaterial> CreateMaterialAsync(MaterialRequest request);
    Task<RestaurantMaterial> UpdateMaterialAsync(int id, MaterialRequest request);
    Task DeleteMaterialAsync(int id);
    Task<IEnumerable<RestaurantPurchaseRequest>> GetPurchaseRequestsAsync(RestaurantErpFilter filter);
    Task<RestaurantPurchaseRequest> CreatePurchaseRequestAsync(PurchaseRequestRequest request);
    Task<RestaurantPurchaseRequest> UpdatePurchaseRequestAsync(int id, PurchaseRequestRequest request);
    Task DeletePurchaseRequestAsync(int id);
    Task SubmitPurchaseRequestAsync(int id, ApprovalDecisionRequest request);
    Task ApprovePurchaseRequestAsync(int id, ApprovalDecisionRequest request);
    Task RejectPurchaseRequestAsync(int id, ApprovalDecisionRequest request);
    Task<RestaurantPurchaseOrder> CreatePurchaseOrderAsync(PurchaseOrderRequest request);
    Task<RestaurantPurchaseOrder> CreatePurchaseOrderFromRequestAsync(int purchaseRequestId, PurchaseOrderRequest request);
    Task<IEnumerable<RestaurantPurchaseOrder>> GetPurchaseOrdersAsync(RestaurantErpFilter filter);
    Task<RestaurantPurchaseOrder> UpdatePurchaseOrderAsync(int id, PurchaseOrderRequest request);
    Task DeletePurchaseOrderAsync(int id);
    Task SetPurchaseOrderStatusAsync(int id, string status);
    Task<IEnumerable<RestaurantGoodsReceipt>> GetGoodsReceiptsAsync(RestaurantErpFilter filter);
    Task<RestaurantGoodsReceipt> CreateGoodsReceiptAsync(GoodsReceiptRequest request);
    Task<RestaurantGoodsReceipt> UpdateGoodsReceiptAsync(int id, GoodsReceiptRequest request);
    Task DeleteGoodsReceiptAsync(int id);
    Task<IEnumerable<RestaurantStockBalance>> GetStockBalancesAsync(string? companyCode);
    Task<IEnumerable<RestaurantPaymentRequest>> GetPaymentRequestsAsync(RestaurantErpFilter filter);
    Task<RestaurantPaymentRequest> CreatePaymentRequestAsync(PaymentRequestRequest request);
    Task<RestaurantPaymentRequest> UpdatePaymentRequestAsync(int id, PaymentRequestRequest request);
    Task DeletePaymentRequestAsync(int id);
    Task SubmitPaymentRequestAsync(int id, ApprovalDecisionRequest request);
    Task ApprovePaymentRequestAsync(int id, ApprovalDecisionRequest request);
    Task RejectPaymentRequestAsync(int id, ApprovalDecisionRequest request);
    Task<RestaurantDisbursement> DisburseAsync(int paymentRequestId, DisbursementRequest request);
    Task<IEnumerable<RestaurantDisbursement>> GetDisbursementsAsync(string? companyCode);
    Task<RestaurantDisbursement> UpdateDisbursementAsync(int id, DisbursementRequest request);
    Task DeleteDisbursementAsync(int id);
    Task<IEnumerable<RestaurantSupplierDebt>> GetSupplierDebtsAsync(RestaurantErpFilter filter);
    Task<RestaurantSupplierDebt> CreateSupplierDebtAsync(SupplierDebtRequest request);
    Task<RestaurantSupplierDebt> UpdateSupplierDebtAsync(int id, SupplierDebtRequest request);
    Task DeleteSupplierDebtAsync(int id);
    Task<IEnumerable<RestaurantCustomerDebt>> GetCustomerDebtsAsync(RestaurantErpFilter filter);
    Task<RestaurantCustomerDebt> CreateCustomerDebtAsync(CustomerDebtRequest request);
    Task<RestaurantCustomerDebt> UpdateCustomerDebtAsync(int id, CustomerDebtRequest request);
    Task DeleteCustomerDebtAsync(int id);
    Task<RestaurantCustomerDebtReceipt> ReceiveCustomerDebtAsync(int customerDebtId, CustomerDebtReceiptRequest request);
    Task<IEnumerable<RestaurantApprovalHistory>> GetApprovalHistoriesAsync(string documentType, int documentId);
    Task<RestaurantAttachment> AddAttachmentAsync(AttachmentRequest request);
    Task<IEnumerable<RestaurantAttachment>> GetAttachmentsAsync(string documentType, int documentId);
}
